# Generated by Django 4.0.5 on 2022-06-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Начало работы')),
                ('end_date', models.DateField(blank=True, verbose_name='Окончание')),
                ('company_name', models.CharField(max_length=100, verbose_name='Название компании')),
                ('position', models.CharField(max_length=150, verbose_name='Должность')),
                ('responsibilities', models.TextField(max_length=2500, verbose_name='Обязанности')),
            ],
        ),
    ]
