# Generated by Django 4.0.5 on 2022-06-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workexperience',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='start_date',
        ),
        migrations.AddField(
            model_name='workexperience',
            name='end_month',
            field=models.CharField(choices=[('Январь', 'Январь'), ('Февраль', 'Февраль'), ('Март', 'Март')], default='Январь', max_length=10, verbose_name='Месяц окончания'),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='end_year',
            field=models.PositiveSmallIntegerField(default=2000, verbose_name='Год окончания'),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='start_month',
            field=models.CharField(choices=[('Январь', 'Январь'), ('Февраль', 'Февраль'), ('Март', 'Март')], default='Январь', max_length=10, verbose_name='Месяц начала работы'),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='start_year',
            field=models.PositiveSmallIntegerField(default=1999, verbose_name='Год начала работы'),
        ),
    ]
