# Generated by Django 4.0.5 on 2022-06-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_workexperience_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.PositiveSmallIntegerField(verbose_name='Год начала обучения')),
                ('end_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год окончания обучения')),
                ('title', models.CharField(max_length=150, verbose_name='Название учреждения')),
                ('faculty', models.CharField(max_length=150, verbose_name='Название факультета')),
                ('department', models.CharField(max_length=150, verbose_name='Название отделения')),
                ('description', models.TextField(max_length=2500, verbose_name='Описание')),
            ],
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='end_month',
            field=models.CharField(blank=True, choices=[('Январь', 'Январь'), ('Февраль', 'Февраль'), ('Март', 'Март'), ('Апрель', 'Апрель'), ('Май', 'Май'), ('Июнь', 'Июнь'), ('Июль', 'Июль'), ('Август', 'Август'), ('Сентябрь', 'Сентябрь'), ('Октябрь', 'Октябрь'), ('Ноябрь', 'Ноябрь'), ('Декабрь', 'Декабрь')], max_length=10, verbose_name='Месяц окончания'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='end_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год окончания'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='start_month',
            field=models.CharField(choices=[('Январь', 'Январь'), ('Февраль', 'Февраль'), ('Март', 'Март'), ('Апрель', 'Апрель'), ('Май', 'Май'), ('Июнь', 'Июнь'), ('Июль', 'Июль'), ('Август', 'Август'), ('Сентябрь', 'Сентябрь'), ('Октябрь', 'Октябрь'), ('Ноябрь', 'Ноябрь'), ('Декабрь', 'Декабрь')], max_length=10, verbose_name='Месяц начала работы'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='start_year',
            field=models.PositiveSmallIntegerField(verbose_name='Год начала работы'),
        ),
    ]
