# Generated by Django 4.0.5 on 2022-06-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_education_alter_workexperience_end_month_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('subject', models.CharField(max_length=250, verbose_name='Тема сообщения')),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=5000, verbose_name='Сообщение')),
            ],
        ),
    ]
