# Generated by Django 4.0.5 on 2022-06-14 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_offers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Offers',
            new_name='Offer',
        ),
    ]
