# Generated by Django 4.0.5 on 2022-06-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_rename_offers_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
