# Generated by Django 4.0.5 on 2022-06-14 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_offer_comment_offer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
