# Generated by Django 4.0.5 on 2022-06-14 20:26

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_offer_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_heading', models.CharField(max_length=100, verbose_name='Название рубрики')),
                ('class_heaging', models.CharField(max_length=100, verbose_name='Bootstrap класс иконки')),
                ('url', models.SlugField(max_length=160)),
                ('is_active', models.BooleanField(default=False, verbose_name='Отображать рубрику активной')),
            ],
        ),
        migrations.CreateModel(
            name='MyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Фамилия Имя')),
                ('speciality', models.CharField(max_length=100, verbose_name='Специальность')),
                ('age', models.PositiveSmallIntegerField(verbose_name='Возраст')),
                ('languages', models.CharField(max_length=150, verbose_name='Языки')),
                ('email', models.EmailField(max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('about', models.TextField(max_length=2500, verbose_name='Обо мне')),
                ('link_facebook', models.SlugField(max_length=150, verbose_name='Ссылка на Facebook')),
                ('title_facebook', models.CharField(max_length=100, verbose_name='Надпись при наведении на Facebook')),
                ('class_facebook', models.CharField(default='fa fa-facebook', max_length=100, verbose_name='Bootstrap класс иконки Facebook')),
                ('link_vk', models.SlugField(max_length=150, verbose_name='Ссылка на Vk')),
                ('title_vk', models.CharField(max_length=100, verbose_name='Надпись при наведении на Vk')),
                ('class_vk', models.CharField(default='fa fa-vk', max_length=100, verbose_name='Bootstrap класс иконки Vk')),
                ('link_github', models.SlugField(max_length=150, verbose_name='Ссылка на Github')),
                ('title_github', models.CharField(max_length=100, verbose_name='Надпись при наведении на Github')),
                ('class_github', models.CharField(default='fa fa-github', max_length=100, verbose_name='Bootstrap класс иконки Github')),
                ('link_linkedin', models.SlugField(max_length=150, verbose_name='Ссылка на LinkedIn')),
                ('title_linkedin', models.CharField(max_length=100, verbose_name='Надпись при наведении на LinkedIn')),
                ('class_linkedin', models.CharField(default='fa fa-linkedin', max_length=100, verbose_name='Bootstrap класс иконки LinkedIn')),
                ('link_telegram', models.SlugField(max_length=150, verbose_name='Ссылка на Telegram')),
                ('title_telegram', models.CharField(max_length=100, verbose_name='Надпись при наведении на Telegram')),
                ('class_telegram', models.CharField(default='fa fa-telegram', max_length=100, verbose_name='Bootstrap класс иконки Telegram')),
                ('avatar', models.ImageField(upload_to='myinfo/', verbose_name='Аватар')),
            ],
        ),
        migrations.CreateModel(
            name='MySkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название технологии')),
                ('level', models.PositiveSmallIntegerField(verbose_name='Уровень понимания')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Имя(ник) заказчика')),
                ('where', models.CharField(max_length=150, verbose_name='Источник отзыва (площадка)')),
                ('order_name', models.CharField(max_length=250, verbose_name='Название заказа')),
                ('review', models.TextField(max_length=2500, verbose_name='Комментарий')),
                ('avatar', models.ImageField(upload_to='reviews/', verbose_name='Аватар')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название работы')),
                ('description', models.TextField(max_length=2500, verbose_name='Описание')),
                ('link', models.CharField(max_length=150, verbose_name='Ссылка на работу в мире')),
                ('link_github', models.SlugField(max_length=150, verbose_name='Ссылка на Github')),
                ('poster', models.ImageField(upload_to='portfolio/', verbose_name='Постер')),
                ('graft', models.BooleanField(default=False, verbose_name='Черновик')),
                ('heading', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.heading', verbose_name='Рубрика')),
            ],
        ),
    ]
