# Generated by Django 4.0.5 on 2022-06-15 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_heading_myinfo_myskill_review_portfolio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='review',
            name='avatar',
            field=models.ImageField(default='reviews/default.png', upload_to='reviews/', verbose_name='Аватар'),
        ),
    ]
