# Generated by Django 4.0.5 on 2022-06-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_rename_review_review_description_alter_review_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Отображать отзыв первым'),
        ),
    ]
