# Generated by Django 4.0.5 on 2022-06-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_review_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myinfo',
            name='link_facebook',
            field=models.CharField(max_length=150, verbose_name='Ссылка на Facebook'),
        ),
        migrations.AlterField(
            model_name='myinfo',
            name='link_github',
            field=models.CharField(max_length=150, verbose_name='Ссылка на Github'),
        ),
        migrations.AlterField(
            model_name='myinfo',
            name='link_linkedin',
            field=models.CharField(max_length=150, verbose_name='Ссылка на LinkedIn'),
        ),
        migrations.AlterField(
            model_name='myinfo',
            name='link_telegram',
            field=models.CharField(max_length=150, verbose_name='Ссылка на Telegram'),
        ),
        migrations.AlterField(
            model_name='myinfo',
            name='link_vk',
            field=models.CharField(max_length=150, verbose_name='Ссылка на Vk'),
        ),
    ]
