# Generated by Django 4.0.5 on 2022-06-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_alter_myinfo_link_facebook_alter_myinfo_link_github_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название в админке')),
                ('title', models.CharField(max_length=100, verbose_name='Надпись при наведении на иконку')),
                ('link', models.CharField(max_length=150, verbose_name='Ссылка на страницу')),
                ('boot_class', models.CharField(default='fa fa-facebook', max_length=100, verbose_name='Bootstrap класс иконки')),
            ],
        ),
        migrations.RemoveField(
            model_name='myinfo',
            name='class_facebook',
        ),
        migrations.RemoveField(
            model_name='myinfo',
            name='class_github',
        ),
        migrations.RemoveField(
            model_name='myinfo',
            name='class_linkedin',
        ),
        migrations.RemoveField(
            model_name='myinfo',
            name='class_telegram',
        ),
        migrations.RemoveField(
            model_name='myinfo',
            name='class_vk',
        ),
        migrations.RemoveField(
            model_name='myinfo',
            name='link_facebook',
        ),
        migrations.RemoveField(
            model_name='myinfo',
            name='link_github',
        ),
        migrations.RemoveField(
            model_name='myinfo',
            name='link_linkedin',
        ),
        migrations.RemoveField(
            model_name='myinfo',
            name='link_telegram',
        ),
        migrations.RemoveField(
            model_name='myinfo',
            name='link_vk',
        ),
        migrations.RemoveField(
            model_name='myinfo',
            name='title_facebook',
        ),
        migrations.RemoveField(
            model_name='myinfo',
            name='title_github',
        ),
        migrations.RemoveField(
            model_name='myinfo',
            name='title_linkedin',
        ),
        migrations.RemoveField(
            model_name='myinfo',
            name='title_telegram',
        ),
        migrations.RemoveField(
            model_name='myinfo',
            name='title_vk',
        ),
    ]
