# Generated by Django 4.0.5 on 2022-06-20 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_alter_myinfo_email_alter_myinfo_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='graft',
            new_name='draft',
        ),
    ]
