# Generated by Django 4.0.5 on 2022-06-20 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_rename_graft_portfolio_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='link_github',
            field=models.CharField(max_length=150, verbose_name='Ссылка на Github'),
        ),
    ]
